---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kured
    chart: kured-1.1.1
    heritage: Tiller
    release: kured
  name: kured
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
  - get
- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kured
    chart: kured-1.1.1
    heritage: Tiller
    release: kured
  name: kured
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kured
subjects:
- kind: ServiceAccount
  name: kured
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: kured
    chart: kured-1.1.1
    heritage: Tiller
    release: kured
  name: kured
  namespace: kube-system
rules:
- apiGroups:
  - extensions
  resourceNames:
  - kured
  resources:
  - daemonsets
  verbs:
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: kured
    chart: kured-1.1.1
    heritage: Tiller
    release: kured
  name: kured
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kured
subjects:
- kind: ServiceAccount
  name: kured
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kured
    chart: kured-1.1.1
    heritage: Tiller
    release: kured
  name: kured
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kured
      release: kured
  template:
    metadata:
      labels:
        app: kured
        release: kured
    spec:
      containers:
      - args:
        - --ds-name=kured
        - --ds-namespace=kube-system
        - --prometheus-url=http://prometheus-server.prometheus.svc.cluster.local
        command:
        - /usr/bin/kured
        env:
        - name: KURED_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/weaveworks/kured:1.1.0
        imagePullPolicy: IfNotPresent
        name: kured
        resources: null
        securityContext:
          privileged: true
      hostPID: true
      restartPolicy: Always
      serviceAccountName: kured
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy:
    type: OnDelete

